version: '1.0'

services:
    db_postgres:
        image: postgres
        container_name: Postgres
        restart: always
        environment:
            POSTGRES_USER: teste
            POSTGRES_PASSWORD: teste123

        ports:
            - "15432:5432"
        volumes:
            - ./dados_banco:/var/lib/postgresql/data

#criar pasta nesse diretório com nome dados_banco
#apos, exececutar 
#docker-compose up -d
#os dados do banco serão gerados na pasta dados_banco
#caso realizar push, limpar pasta anteriormente ou apagar caso deletar dados
