version: '3.8'

services:
  pgadmin4:
    image: dpage/pgadmin4:8.10
    environment:
      PGADMIN_DEFAULT_EMAIL: "XXXXXXXXXXXX"
      PGADMIN_DEFAULT_PASSWORD: "XXXXXXXXXXXX"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  pgadmin_data: