version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "XXXXXXXXXXXXXXX"
    ports:
      - "5432:5432"
    volumes:
      - /var/www/data_postgres:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4:8.11
    environment:
      PGADMIN_DEFAULT_EMAIL: "XXXXXXXXXXXXXXX"
      PGADMIN_DEFAULT_PASSWORD: "XXXXXXXXXXXXXXX"
    ports:
      - "5050:80"