version: '3.9'

services:
  jenkins:
    build:
      context: .
    ports:
      - '8084:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
    restart: on-failure
    mem_limit: 600m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx600m

volumes:
  jenkins_home:
    driver: local
